CREATE TABLE [dbo].[Teams]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
	[Name] NVARCHAR(100) NOT NULL,
	[JoinDate] DateTime NOT NULL
)


CREATE TABLE [dbo].[Contestants]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
	[Name] NVARCHAR(100) NOT NULL,
	[TeamId] UNIQUEIDENTIFIER NOT NULL, 
    [DominantHand] INT NOT NULL, 
    CONSTRAINT [FK_Contestant_Team] FOREIGN KEY ([TeamId]) REFERENCES [Teams]([Id])
)


CREATE TABLE [dbo].[Umpires]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY, 
    [Name] NVARCHAR(50) NOT NULL,
    [TotalMatchStops] INT NOT NULL
)


CREATE TABLE [dbo].[Matches]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
	[HomeTeamId] UNIQUEIDENTIFIER NOT NULL , 
    [AwayTeamId] UNIQUEIDENTIFIER NOT NULL, 
    [Date] DATETIMEOFFSET NOT NULL, 
    [HomeOdds] DECIMAL(10,2) NOT NULL, 
    [AwayOdds] DECIMAL(10,2) NOT NULL, 
    [UmpireId] UNIQUEIDENTIFIER NOT NULL,
	[WinningTeamId] UNIQUEIDENTIFIER NULL,

    CONSTRAINT [FK_Matches_HomeTeams] FOREIGN KEY ([HomeTeamId]) REFERENCES [Teams]([Id]),
    CONSTRAINT [FK_Matches_AwayTeams] FOREIGN KEY ([AwayTeamId]) REFERENCES [Teams]([Id]),
    CONSTRAINT [FK_Matches_WinningTeams] FOREIGN KEY ([WinningTeamId]) REFERENCES [Teams]([Id]),
    CONSTRAINT [FK_Matches_Umpires] FOREIGN KEY ([UmpireId]) REFERENCES [Umpires]([Id])
)


CREATE TABLE [dbo].[Venues]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
	[Name] NVARCHAR(100) NOT NULL,
	[Capacity] INT NOT NULL
)


CREATE TABLE [dbo].[Tickets]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
	[MatchId] UNIQUEIDENTIFIER NOT NULL,
	[Price] DECIMAL(10,2) NOT NULL,
	[Seat] NVARCHAR(10) NOT NULL,
	[VenueId] UNIQUEIDENTIFIER NOT NULL

	CONSTRAINT [FK_Tickets_Matches] FOREIGN KEY ([MatchId]) REFERENCES [Matches]([Id]),
	CONSTRAINT [FK_Tickets_Venues] FOREIGN KEY ([VenueId]) REFERENCES [Venues]([Id])
)

CREATE TABLE [dbo].[Doctors]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
	[Name] NVARCHAR(50) NOT NULL,
)
